#
# Module manifest for module 'PPDM-pwsh'
#
# Generated by: Karsten.Bott@dell.com
#
# Generated on: 03/09/2020
#

@{

# Script module or binary module file associated with this manifest.
RootModule = 'PPDM-pwsh.psm1'

# Version number of this module.
ModuleVersion = '19.14.20.3'

# Supported PSEditions
# CompatiblePSEditions = @()

# ID used to uniquely identify this module
GUID = '779958a6-5b27-44b0-a37d-cb0db8f068e7'

# Author of this module
Author = 'karsten.bott@dell.com'

# Company or vendor of this module
CompanyName = 'Private build by individual'

# Copyright statement for this module
Copyright = '(c) 2023 karsten.bott@dell.com. All rights reserved.'

# Description of the functionality provided by this module
Description = 'Powershell Module to interact with the PowerProdect Data Manager (PPDM) API'

# Minimum version of the Windows PowerShell engine required by this module
# PowerShellVersion = ''

# Name of the Windows PowerShell host required by this module
# PowerShellHostName = ''

# Minimum version of the Windows PowerShell host required by this module
# PowerShellHostVersion = ''

# Minimum version of Microsoft .NET Framework required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# DotNetFrameworkVersion = ''

# Minimum version of the common language runtime (CLR) required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# CLRVersion = ''

# Processor architecture (None, X86, Amd64) required by this module
# ProcessorArchitecture = ''

# Modules that must be imported into the global environment prior to importing this module
# RequiredModules = @()

# Assemblies that must be loaded prior to importing this module
# RequiredAssemblies = @()

# Script files (.ps1) that are run in the caller's environment prior to importing this module.
# ScriptsToProcess = @()

# Type files (.ps1xml) to be loaded when importing this module
# TypesToProcess = @()

# Format files (.ps1xml) to be loaded when importing this module
# FormatsToProcess = @()

# Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
NestedModules = @(
    './errors/errors',
    './modules/clouddr',
    './modules/storage',
    './modules/cndm',
    './modules/credentials',
    './modules/agents',
    './modules/assets',
    './modules/activity',
    './modules/protection_policies',
    './modules/certificates',
    './modules/inventory',
    './modules/copies',
    './modules/user',
    './modules/monitoring',
    './modules/sdr',
    './modules/locations',
    './modules/appliance-management',
    './modules/license',
    './modules/restored-copies',
    './modules/upgrade-packages',
    './modules/discoveries',
    './modules/protection-engines',
    './modules/restore-plans',
    './modules/rules',
    './modules/flr',
    './modules/common',
    './modules/sso-mfa',
    './modules/identity-providers'
)

# Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
FunctionsToExport = @(
    'Wait-PPDMApplianceFresh',
    'Connect-PPDMapiEndpoint',
    'Disconnect-PPDMsession',
    'Get-PPDMassets',
    'Set-PPDMassets',
    'Get-PPDMhosts',
    'Get-PPDMactivities',
    'Restart-PPDMactivities',
    'Stop-PPDMactivities',
    'New-PPDMUsers',
    'Unblock-PPDMSSLCerts',
    'Update-PPDMAccessToken',
    'Invoke-PPDMapirequest',
    'Start-PPDMasset_backups',
    'Get-PPDMprotection_engines',
    'Get-PPDMprotectionEngineProxies',
    'New-PPDMProtectionEngineProxy'
    'Remove-PPDMProtectionEngineProxy',
    'Disable-PPDMProtectionEngineProxy',
    'Get-PPDMprotection_policies',
    'New-PPDMprotection_policies',
    'Get-PPDMdiscoveries',
    'Set-PPDMdiscoveries',
    'Start-PPDMprotection_policies',
    'Start-PPDMdiscoveries',
    'Update-PPDMtoken',
    'Get-PPDMcommon_settings',
    'Set-PPDMcommon_settings',
    'Get-PPDMinventory_sources',  
    'Set-PPDMinventory_sources',
    'Get-PPDMvcenterDatastores',  
    'Add-PPDMinventory_sources',
    'Remove-PPDMinventory_sources',   
    'Get-PPDMcomponents',
    'Get-PPDMdatacomponents',
    'Get-PPDMconfigurations',
    'Set-PPDMconfigurations',
    'Get-PPDMconfigStatus',
    'Get-PPDMnodes',
    'Set-PPDMnodes',    
    'Get-PPDMDisks',
    'Get-PPDMcloud_dr_accounts',
    'Set-PPDMcloud_dr_accounts',
    'Set-PPDMcomponents',
    'Remove-PPDMcomponents',    
    'Get-PPDMdata_targets',
    'Get-PPDMdatadomain_mtrees',
    'Get-PPDMstorage_systems',
    'Set-PPDMstorage_systems',
    'Remove-PPDMstorage_systems',
    'Get-PPDMcloud_dr_server_deployment',
    'Get-PPDMcloud_dr_server_version',
    'Get-PPDMTELEMETRY_SETTING',
    'Get-PPDMcloud_dr_data_targets',
    'Get-PPDMcloud_dr_storage_containers',
    'Get-PPDMcloud_dr_server_configuration',
    'Get-PPDMcloud_dr_sessions',
    'Get-PPDMcloud_dr_vcenters',
    'Get-PPDMdatadomain_cloud_units',
    'Get-PPDMkubernetes_clusters',
    'Get-PPDMpvc_storage_class_mappings',
    'Get-PPDMdatadomain_ddboost_encryption_settings',
    'Get-PPDMcredentials',
    'New-PPDMcredentials',
    'Remove-PPDMcredentials',
    'Update-PPDMcredentials',
   # 'Get-PPDMagents_list',
    'Get-PPDMagent_registration_status',
    'Get-PPDMalerts',
    'Set-PPDMalerts_acknowledgement',
    'Get-PPDMcopy_map',
    'Get-PPDMactivity_metrics',
    'Approve-PPDMEula',
    'Add-PPDMCertificates',
    'Get-PPDMCertificates',
    'Update-PPDMCertificates',
    'Approve-PPDMCertificates',
    'Remove-PPDMCertificates',
    'Get-PPDMCopies',
    'Remove-PPDMCopies',
    'Get-PPDMUser_groups',
    'Get-PPDMUsers',
    'Get-PPDMroles',
    'Get-PPDMWebException',
    'Get-PPDMprotection_details',
    'Get-PPDMlatest_copies',
    'Get-PPDMTimezones',
    'Get-PPDMserver_disaster_recovery_configurations',
    'Set-PPDMserver_disaster_recovery_configurations',
    'Get-PPDMserver_disaster_recovery_backups',
    'New-PPDMserver_disaster_recovery_backups',
    'Remove-PPDMserver_disaster_recovery_backups',
    'Update-PPDMserver_disaster_recovery_backups',
    'Get-PPDMserver_disaster_recovery_hosts',
    'Get-PPDMserver_disaster_recovery_status',
    'Get-PPDMLocations',
    'New-PPDMLocations',
    'Remove-PPDMLocations',
    'Get-PPDMProtection_rules',
    'New-PPDMProtection_rules',
    'Remove-PPDMProtection_rules',
    'Set-PPDMProtection_rules',
    'Get-PPDMsmtp',
    'New-PPDMsmtp',
    'Set-PPDMsmtp',
    'Remove-PPDMsmtp',
    'Get-PPDMprotection_storage_metrics',
    'New-PPDMVMPrimaryBackupPolicy',
    'Remove-PPDMprotection_policies',
    'Add-PPDMProtection_policy_assignment',
    'Remove-PPDMProtection_policy_assignment',
    'New-PPDMBackupSchedule',
    'New-PPDMVMBackupPolicy',
    'New-PPDMFSBackupPolicy',
    'New-PPDMDatabaseBackupSchedule',
    'New-PPDMSQLBackupPolicy',
    'New-PPDMExchangeBackupPolicy',
    'New-PPDMK8SBackupPolicy',    
    'Set-PPDMcertificates',
    'Start-PPDMprotection',
    'Get-PPDMLicenses',
    'Set-PPDMLicenses',
    'Get-PPDMassetcopies',
    'Restore-PPDMK8Scopies',
    'Get-PPDMupgrade_packages',
    'Stop-PPDMupgrade',
    'Get-PPDMPasswordPolicies',
    'Set-PPDMPasswordPolicies',
    'Remove-PPDMcdrs',
    'Remove-PPDMupgrade',
    'Stop-PPDMupgradePrecheck',
    'Request-PPDMActivityLog',  
    'Save-PPDMActivityLog',
    'Restore-PPDMVMcopies',
    'Get-PPDMAudit_logs',
    'Update-PPDMAudit_logs',
    'Get-PPDMrestore_plans'
    'Get-PPDMRestorePlans',
    'Get-PPDMrules',
    'Start-PPDMflr_sessions',
    'Get-PPDMflr_sessions',
    'Get-PPDMflr_filelisting',
    'Set-PPDMflr_sessions',    
    'Remove-PPDMflr_sessions',
    'Restore-PPDMflr_sessions',
    'Get-PPDMRestored_copies',
    'New-PPDMRestored_copies',
    'Get-PPDMFSAgentFLRBrowselist',
    'Restore-PPDMFileFLR_copies',
    'Restore-PPDMMSSQL_copies',
    'Get-PPDMstorage_system_metrics',
    'Get-PPDMasset_protection_metrics',
    'Set-PPDMapp_hosts',
    'Get-PPDMprotection_groups',
    'Get-PPDMagents_update_sessions',       
    'Get-PPDMwhitelist',
    'Set-PPDMagents_update_sessions',
    'Remove-PPDMagents_update_sessions',
    'Get-PPDMEula',
    'Get-PPDMactivity_categories',
    'Get-PPDMsystem_health_issues',
    'Get-PPDMsystem_health_score_categories',
    'Remove-PPDMcloud_dr_server_deployment',
    'Get-PPDMinfrastructure_nodes',
    'New-PPDMprotection_groups',
    'Get-PPDMdatadomain_storage_units',
    'New-PPDMdatadomain_storage_units',
    'Remove-PPDMdatadomain_storage_units',
    'New-PPDMdatadomain_mtrees',
    'Get-PPDMcopies_query',
    'Get-PPDMvm_backup_setting',
    'Set-PPDMvm_backup_setting',
    'Get-PPDMmfa_securids',
    'New-PPDMmfa_securids',
    'Remove-PPDMmfa_securids',
    'Set-PPDMmfa_securids',
    'Get-PPDMidentity_providers',
    'Set-PPDMmfa_bypass_accounts',
    'Get-PPDMmfa_bypass_accounts',
    'Remove-PPDMmfa_bypass_accounts'     
    )

# Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
CmdletsToExport = @()

# Variables to export from this module
VariablesToExport = '*'

# Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
AliasesToExport = @(
    'Get-PPDMVPE',
    'New-PPDMProxy',
    'Get-PPDMProxy',
    'Remove-PPDMProxy',
    'Disable-PPDMProxy',
    'Get-PPDMAssetSource',
    'Set-PPDMAssetSource',
    'New-PPDMAssetSource',
    'Add-PPDMAssetSource',
    'Remove-PPDMAssetSource',
    'Get-PPDMJob',
    'Request-PPDMJobLog',
    'Save-PPDMJobLog',
    'Set-PPDMasset',
    'Restore-PPDMVMasset',
    'Restore-PPDMFLR',
    'Get-PPDMk8sclusters',
    'Get-PPDMk8spvcmappings',
    'Get-PPDMFLRfiles',
    'Set-PPDMFLRbrowsescope',
    'Restore-PPDMDDB_MSSQL',
    'Unregister-PPDMAssetFromPoliy',
    'Start-PPDMPLC',
    'Start-PPDMPLCStage',
    'Start-PPDMProtectionStage',
    'Get-PPDMStorageMetrics',
    'Get-PPDMServiceStatus',
    'Get-PPDMagents',
    'Connect-PPDMSystem',
    'Get-PPDMidp'
)

# DSC resources to export from this module
# DscResourcesToExport = @()

# List of all modules packaged with this module
# ModuleList = @()

# List of all files packaged with this module
# FileList = @()

# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
PrivateData = @{

    PSData = @{

        # Tags applied to this module. These help with module discovery in online galleries.
        Tags = @('PPDM','PowerProtect','PowerProtect_Datamanager','DELLEMC','DELL','BRS')

        # A URL to the license for this module.
        # LicenseUri = ''

        # A URL to the main website for this project.
         ProjectUri = 'https://github.com/bottkars/PPDM-pwsh'

        # A URL to an icon representing this module.
        IconUri = 'https://vectorified.com/images/dell-emc-icon-12.png'

        # ReleaseNotes of this module
        ReleaseNotes = '
        2023-07-20 (v19.14.20.3)
        - added initial mfa and idp support 
        - fixes to pagination, streamlined -page and -pagesuze parameters
        - added default activity views for Protection, Asset and System Jobs
        2023-07-11 (v19.14.20)
        - added FLR Usecases for Agent Backup
        - Further Implementation of Filters
        - implementation of restore groups
        2022-10-05 (v19.11.2)
        - added asset modifications     
        2022-09-07 (v19.11.0)
        - added support for Tanzu Guest Clusters
        - added Module Aliases
        - added support for ProtectionEngineProxies
        2021-06-10 (v19.8.12):
        - added Kubernetes Policy Creation
        - added Kubernetes Restore Workflow
        - uupdated more cmdlets for pagination and filters
        2021-05-25:
        - added license feature for new 19.8        
        2021-05-06:
        - added Pre-Release for new 19.8
        - adeed Protection Policy Managemnt Step 1
        - Introduced Query and Pagination       
        2021-02-13:
        - added alert acknowledgement by id
        2020-11-01:
        - added Server Disaster Recovers
        2020-10-28:
        - adding inventory_sources 
        2020-10-27:
        - added certs management
        2020-10-09:
        Added Miles Features
        - clouddr
        - STorage 
        - SPBM
        2019-12-09:
        Initial module version supporting PDM API 1.5 onwards
        - added diconnect (removes Global Variables )
        - added force connect (removes Global Variables )
        '
    # Prerelease = 'Pre'
    } # End of PSData hashtable

} # End of PrivateData hashtable

# HelpInfo URI of this module
# HelpInfoURI = ''

# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
# DefaultCommandPrefix = ''

}

